default:
    image: "rust:latest"

stages:
    - lint
    - test
    - fuzz

variables:
    CARGO_HOME: $CI_PROJECT_DIR/cargo

lint:fmt:
    stage: lint
    before_script:
        - rustup component add rustfmt
    script:
        - cargo fmt -- --check

lint:clippy:
    stage: lint
    before_script:
        - apt update -yqq
        - apt install -yqq clang libpq-dev
        - rustup component add clippy
    script: cargo clippy --all-features --all-targets -- --deny warnings

.test: &test
    stage: test
    before_script:
        - MODE=$(echo "$CI_JOB_NAME" | cut -d ':' -f 2)
        - test "$MODE" == "release" && CARGO_FLAGS='--release' || CARGO_FLAGS=''
        - echo "deb http://apt.postgresql.org/pub/repos/apt bookworm-pgdg main" > /etc/apt/sources.list.d/pgdg.list
        - curl https://www.postgresql.org/media/keys/ACCC4CF8.asc > /etc/apt/trusted.gpg.d/ACCC4CF8.asc
        - apt update -yqq
        - apt install -yqq sudo postgresql-17 locales clang libpq-dev
        - echo "en_US UTF-8" > /etc/locale.gen
        - locale-gen en_US.UTF-8
        - sudo -u postgres pg_ctlcluster 17 main start
        - sudo -u postgres psql --command "create role root WITH LOGIN ENCRYPTED PASSWORD '1234' SUPERUSER;";
        - sudo -u postgres psql --command "create database root with owner root;";
        - export DATABASE_URL='host=localhost password=1234'
    script:
        - cargo test --all-features $CARGO_FLAGS

test:debug:
    <<: *test

test:release:
    <<: *test

.fuzz: &fuzz
    <<: *test
    stage: fuzz
    image: rustlang/rust:nightly-bookworm
    script:
        - cargo install cargo-fuzz
        - TARGET=$(echo "$CI_JOB_NAME" | cut -d ':' -f 2)
        - cd core
        - cargo  fuzz run fuzz_$TARGET -- -max_total_time=10

fuzz:copy:
    <<: *fuzz

fuzz:exec:
    <<: *fuzz

fuzz:query:
    <<: *fuzz

cache:
    paths:
        - $CARGO_HOME
        - target/
