combine_control_expr=false
control_brace_style="ClosingNextLine"
empty_item_single_line=false
force_multiline_blocks=true
imports_layout="HorizontalVertical"
match_block_trailing_comma=true
max_width=80
newline_style="Unix"
overflow_delimited_expr=true
reorder_impl_items=true
struct_lit_single_line=false
unstable_features=true
use_field_init_shorthand=true
use_try_shorthand=true

[width_heuristics]
attr_fn_like_width = 100
chain_width = 100
fn_call_width = 100
struct_lit_width = 100
struct_variant_width = 100
array_width = 100
single_line_if_else_max_width = 100
