[workspace]
members = [
    "core",
    "cli",
    "derive",
]

[workspace.package]
version = "3.2.0"
authors = ["Sanpi <sanpi@homecomputing.fr>"]
edition = "2021"
license = "MIT"
homepage = "https://elephantry.github.io"
repository = "https://github.com/elephantry/elephantry"
