#!/bin/bash

set -euo pipefail

main()
{
    local version=$1
    local short_version=$(echo "$version" | sed -r 's#\.[0-9]+$##')

    cargo +nightly fmt -- --check
    cargo +nightly clippy --all-features -- --deny warnings
    cargo +nightly test --all-features

    sed -i '0,/version/{s/^version = ".*"/version = "'$version'"/}' derive/Cargo.toml core/Cargo.toml cli/Cargo.toml
    sed -i -r -e '/dependencies\.elephantry/ {n; s/^version = ".*"/version = "'$short_version'"/}' cli/Cargo.toml core/Cargo.toml

    git add RELEASES.md derive/Cargo.toml core/Cargo.toml cli/Cargo.toml
    git commit --message "v$version"
    git tag "$version"

    for crate in derive core cli
    do
        cd $crate

        cargo publish
        sleep 5

        cd -
    done

    git push
    git push --tags
}

main $*
