#!/bin/bash

set -euo pipefail

main()
{
    local version=$1
    local short_version=$(echo "$version" | sed -r 's#\.[0-9]+$##')

    cargo +nightly fmt -- --check
    cargo +nightly clippy --all-features -- --deny warnings
    cargo +nightly test --all-features

    sed -i '0,/version/{s/^version = ".*"/version = "'$version'"/}' Cargo.toml
    sed -i -r -e '/dependencies\.elephantry/ {n; s/^version = ".*"/version = "'$short_version'"/}' cli/Cargo.toml core/Cargo.toml
    sed -i -e "s/\[Unreleased\]/[$version] - $(date +%Y-%m-%d)/" CHANGELOG.md

    git add CHANGELOG.md Cargo.toml derive/Cargo.toml core/Cargo.toml cli/Cargo.toml
    git diff --cached

    read -p "Are you sure? [yN]" -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]
    then
        return 0
    fi

    git commit --message "v$version"
    git tag "$version"

    for crate in derive core cli
    do
        cd $crate

        cargo publish

        cd -
    done

    git push
    git push --tags
}

main $*
