[package]
name = "elephantry-cli"
version = "3.0.0-beta.4"
description = "elephantry cli tool"
repository = "https://github.com/elephantry/elephantry/tree/main/cli"
homepage = "https://elephantry.github.io"
license = "MIT"
authors = ["Sanpi <sanpi@homecomputing.fr>"]
edition = "2021"

[dependencies]
case = "1.0"
dotenv = "0.15"
term-table = "1.1"
thiserror = "1.0"

[dependencies.clap]
version = "3.0"
features = ["derive"]

[dependencies.elephantry]
version = "3.0.0-beta"
features = ["all-types"]
path = "../core/"
