[package]
name = "elephantry-cli"
version = "0.1.0"
description = "elephantry cli tool"
repository = "https://github.com/sanpii/elephantry/tree/master/cli"
homepage = "https://github.com/sanpii/elephantry"
license = "MIT"
authors = ["Sanpi <sanpi@homecomputing.fr>"]
edition = "2018"

[dependencies]
case = "1.0"
dotenv = "0.15"
structopt = "0.3"
term-table = "1.1"

[dependencies.elephantry]
version = "0.1"
path = "../core/"
