[package]
name = "elephantry-cli"
version = "1.7.0"
description = "elephantry cli tool"
repository = "https://github.com/elephantry/elephantry/tree/master/cli"
homepage = "https://elephantry.github.io"
license = "MIT"
authors = ["Sanpi <sanpi@homecomputing.fr>"]
edition = "2018"

[dependencies]
case = "1.0"
dotenv = "0.15"
structopt = "0.3"
term-table = "1.1"
thiserror = "1.0"

[dependencies.elephantry]
version = "1.7"
path = "../core/"
