[package]
name = "elephantry"
description = "Object model manager for PostgreSQL"
repository = "https://github.com/elephantry/elephantry"
homepage = "https://github.com/elephantry/elephantry"
license = "MIT"
version = "0.4.0"
authors = ["Sanpi <sanpi@homecomputing.fr>"]
edition = "2018"
readme = "../README.md"
keywords = ["database", "postgresql"]
categories = ["database"]

[dependencies]
bytes = "0.5"
byteorder = "1.3"
libpq = "0.11"
log = "0.4"
regex = "1.3"

[dependencies.bit-vec]
version = "0.6"
optional = true

[dependencies.bigdecimal]
version = "0.1"
optional = true

[dependencies.chrono]
version = "0.4"
optional = true

[dependencies.macaddr]
version = "1.0.0"
optional = true

[dependencies.elephantry-derive]
path = "../derive"
version = "0.4"

[dependencies.geo-types]
version = "0.6"
optional = true

[dependencies.postgres_money]
version = "0.3"
optional = true

[dependencies.r2d2]
version = "0.8"
optional = true

[dependencies.serde]
version = "1.0"
optional = true

[dependencies.serde_derive]
version = "1.0"
optional = true

[dependencies.serde_json]
version = "1.0"
optional = true

[dependencies.time]
version = "0.2"
optional = true

[dependencies.uuid]
version = "0.8"
optional = true

[dependencies.xmltree]
version = "0.10"
optional = true

[dev-dependencies]
serde_json = "1.0"
uuid = "0.8"
pretty_env_logger = "0.4"

[dev-dependencies.async-std]
version= "1.6"
features = ["attributes"]

[features]
default = []
bit = ["bit-vec"]
date = ["chrono"]
geo = ["geo-types"]
json = ["serde_json"]
money = ["postgres_money"]
numeric = ["bigdecimal"]
net = ["macaddr"]
serde-support = ["serde", "serde_derive"]
xml = ["xmltree"]

[[example]]
name = "02-query"
required-features = ["date", "numeric"]

[[example]]
name = "03-read"
required-features = ["date", "numeric"]

[[example]]
name = "04-write"
required-features = ["date", "numeric"]

[[example]]
name = "05-extra"
required-features = ["date", "numeric"]

[[example]]
name = "06-complex"
required-features = ["date", "numeric"]

[[example]]
name = "07-relations"
required-features = ["date", "numeric"]

[[example]]
name = "08-async"
required-features = ["date", "numeric"]

[badges]
gitlab = { repository = "elephantry/elephantry", branch = "master" }
