on: [pull_request, push]

env:
  CARGO_TERM_COLOR: always

jobs:
  lint_fmt:
    name: cargo fmt
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt
      - name: Check formating
        run: cargo fmt -- --check

  lint_clippy:
    name: Clippy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy
      - name: Run clippy
        run: cargo clippy --all-features --all-targets -- --deny warnings

  lint_shear:
    name: Shear
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Install cargo-shear
        run: cargo install cargo-shear
      - name: Run cargo-shear
        run: cargo shear --deny-warnings

  tests:
    name: Tests
    strategy:
      matrix:
        mode: ["debug", "release"]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - uses: ikalnytskyi/action-setup-postgres@v8
        id: postgres

      - name: Run tests (debug)
        if: matrix.mode == 'debug'
        run: RUST_TEST_THREADS=1 cargo test --all-features
        env:
          PGSERVICE: ${{ steps.postgres.outputs.service-name }}

      - name: Run tests (release)
        if: matrix.mode == 'release'
        run: RUST_TEST_THREADS=1 cargo test --all-features --release
        env:
          PGSERVICE: ${{ steps.postgres.outputs.service-name }}

  fuzz:
    name: Fuzz
    strategy:
      matrix:
        target: ["copy", "exec", "query"]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: nightly
      - uses: ikalnytskyi/action-setup-postgres@v8
        id: postgres

      - name: Install fuzz
        run: cargo install cargo-fuzz
      - name: Run fuzz
        working-directory: ./core
        run: cargo fuzz run fuzz_${{ matrix.target }} -- -max_total_time=10
        env:
          PGSERVICE: ${{ steps.postgres.outputs.service-name }}
